- name: Install astro pkg on Reterminal
  gather_facts: false
  hosts: all
  tasks:
    - name: Get the current user
      command: whoami
      register: whoami
    
    - set_fact:
        ansible_user: "{{ whoami.stdout }}"

    - name: Add ppa
      become: true
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:mutlaqja/ppa
        - ppa:pch/phd2

    - name: Install astro pkg
      become: true
      apt:
        pkg: 
          - kstars-bleeding
          - indi-full
          - phd2
        state: present
        update_cache: true

    - name: Disable XFCE4 standby
      shell: |
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/blank-on-ac -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-enabled -s false -n -t bool
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-ac-off -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-ac-sleep -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-battery-off -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-battery-sleep -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-on-ac -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-on-battery -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-ac -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-battery -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/hibernate-timeout-ac -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/hibernate-timeout-battery -s 0 -n -t int
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lock-screen-suspend-hibernate -s false -n -t bool

    # - name: clone git@github.com:jujax/astroqtpy.git
    #   git:
    #     repo: git@github.com:jujax/astroqtpy.git
    #     dest: /home/{{ansible_user}}/astroqtpy

    - name: Install desktop shortcut
      copy:
        src: ./files/astroqtpy.desktop
        dest: /home/{{ansible_user}}/astroqtpy/astroqtpy.desktop
        mode: 0755

    - name: Create autostart dir
      file:
        path: /home/{{ansible_user}}/.config/autostart
        state: directory
        mode: 0755
    
    - name: autolaunch at startup
      copy:
        src: ./files/astroqtpy.desktop
        dest: /home/{{ansible_user}}/.config/autostart/autolaunch-astroqtpy.desktop
        mode: 0755