- name: Install astro pkg
  gather_facts: false
  hosts: all
  tasks:
    - name: Get the current user
      command: whoami
      register: whoami
    
    - set_fact:
        ansible_user: "{{ whoami.stdout }}"

    - name: Add ppa
      become: true
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:mutlaqja/ppa
        - ppa:pch/phd2

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
        
    - name: Install astro pkg
      become: true
      apt:
        pkg: "{{ item }}"
        state: present
      loop:
          - kstars-bleeding
          - indi-full
          - phd2